services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: docker-practz-app
    container_name: docker-practz-app
    restart: always
    ports:
      - "3000:3000"
    # tty: true
    # environment:
    #   SERVICE_NAME: app
    #   SERVICE_TAGS: dev
    # volumes:
    #   - data:/var/www/html
    networks:
      - docker-practz-network

networks:
  docker-practz-network:
    driver: bridge

volumes:
  data:
    driver: local

